// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProTrack.Data;

#nullable disable

namespace ProTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108132953_ExpandDemoClients")]
    partial class ExpandDemoClients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceTimeEntries", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("TimeEntriesId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId", "TimeEntriesId");

                    b.HasIndex("TimeEntriesId");

                    b.ToTable("InvoiceTimeEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProTrack.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "demo-user-123",
                            AccessFailedCount = 0,
                            Address = "123 Demo Street, Demo City, DC 12345",
                            CompanyName = "Demo Company",
                            ConcurrencyStamp = "9cef744a-cacd-40cd-a4c3-63a6f8639781",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7480),
                            Email = "demo@protrack.com",
                            EmailConfirmed = true,
                            FirstName = "Demo",
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "DEMO@PROTRACK.COM",
                            NormalizedUserName = "DEMO@PROTRACK.COM",
                            PhoneNumber = "+1-555-0123",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9a73947e-d033-4fa4-8483-ff7f0b526e6a",
                            TwoFactorEnabled = false,
                            UserName = "demo@protrack.com"
                        });
                });

            modelBuilder.Entity("ProTrack.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "456 Innovation Drive, Silicon Valley, CA 94000",
                            ContactEmail = "contact@techinnovators.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7772),
                            IsActive = true,
                            Name = "Tech Innovators Corp",
                            Notes = "Leading technology company specializing in cutting-edge software solutions. Known for innovative approaches to complex technical challenges.",
                            PhoneNumber = "+1-555-TECH-001",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "789 Marketing Boulevard, New York, NY 10001",
                            ContactEmail = "info@globalmarketing.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7776),
                            IsActive = true,
                            Name = "Global Marketing Agency",
                            Notes = "Full-service marketing agency with global reach. Expert in digital marketing, brand strategy, and creative campaigns.",
                            PhoneNumber = "+1-555-MARKET-02",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1010 Inspiration Lane, Los Angeles, CA 90012",
                            ContactEmail = "hello@creativevision.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7779),
                            IsActive = true,
                            Name = "Creative Vision Studios",
                            Notes = "Boutique design studio specializing in brand identity, motion graphics, and experiential marketing activations.",
                            PhoneNumber = "+1-555-CREATIVE",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 4,
                            Address = "820 Freight Avenue, Chicago, IL 60654",
                            ContactEmail = "ops@northwindlogistics.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7782),
                            IsActive = true,
                            Name = "Northwind Logistics",
                            Notes = "National logistics provider focused on cold-chain and last-mile delivery optimization.",
                            PhoneNumber = "+1-555-NORTH-01",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 5,
                            Address = "550 Strategy Street, Austin, TX 78701",
                            ContactEmail = "team@brightpathco.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7785),
                            IsActive = true,
                            Name = "BrightPath Consulting",
                            Notes = "Management consulting firm delivering digital transformation roadmaps for mid-market enterprises.",
                            PhoneNumber = "+1-555-BRIGHT-5",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 6,
                            Address = "300 Peaks Plaza, Denver, CO 80202",
                            ContactEmail = "info@summitfg.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7788),
                            IsActive = true,
                            Name = "Summit Financial Group",
                            Notes = "Wealth management and fractional CFO services for high-growth startups and professional services firms.",
                            PhoneNumber = "+1-555-SUMMIT-6",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 7,
                            Address = "88 Sustainability Way, Portland, OR 97205",
                            ContactEmail = "contact@greenearth.org",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7790),
                            IsActive = true,
                            Name = "GreenEarth Initiatives",
                            Notes = "Environmental non-profit coordinating sustainability campaigns, grant programs, and community outreach.",
                            PhoneNumber = "+1-555-GREEN-07",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 8,
                            Address = "212 Wellness Parkway, Boston, MA 02110",
                            ContactEmail = "support@apexhealth.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7793),
                            IsActive = true,
                            Name = "Apex Healthcare Solutions",
                            Notes = "Healthcare technology provider delivering telemedicine platforms and compliance automation.",
                            PhoneNumber = "+1-555-APEX-CARE",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 9,
                            Address = "77 Insight Terrace, Seattle, WA 98104",
                            ContactEmail = "partners@bluewaveanalytics.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7798),
                            IsActive = true,
                            Name = "BlueWave Analytics",
                            Notes = "Data analytics consultancy focusing on predictive modeling, data warehousing, and BI dashboards.",
                            PhoneNumber = "+1-555-WAVE-009",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 10,
                            Address = "640 Skyline Boulevard, Miami, FL 33130",
                            ContactEmail = "studio@urbanedgearch.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7837),
                            IsActive = true,
                            Name = "UrbanEdge Architects",
                            Notes = "Architectural firm creating sustainable mixed-use developments and adaptive reuse projects.",
                            PhoneNumber = "+1-555-URBAN-10",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 11,
                            Address = "400 Commerce Court, Minneapolis, MN 55401",
                            ContactEmail = "hq@silverlineretail.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7839),
                            IsActive = true,
                            Name = "Silverline Retailers",
                            Notes = "Regional retail chain investing in e-commerce modernization and omnichannel fulfillment.",
                            PhoneNumber = "+1-555-SILVER-1",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 12,
                            Address = "950 Innovation Parkway, Detroit, MI 48226",
                            ContactEmail = "projects@nextgenmfg.com",
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7842),
                            IsActive = true,
                            Name = "NextGen Manufacturing",
                            Notes = "Advanced manufacturing company deploying IoT-enabled production lines and robotics integration.",
                            PhoneNumber = "+1-555-NEXTGEN",
                            UserId = "demo-user-123"
                        });
                });

            modelBuilder.Entity("ProTrack.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProTrack.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId", "Title")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7917),
                            Description = "Complete redesign and relaunch of the e-commerce platform with modern UI/UX, improved performance, and enhanced user experience. Includes mobile optimization, payment gateway integration, and analytics implementation.",
                            EndDate = new DateTime(2026, 1, 7, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7916),
                            HourlyRate = 75.00m,
                            LastModified = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7918),
                            StartDate = new DateTime(2025, 10, 9, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7905),
                            Status = 1,
                            Title = "Q4 E-commerce Platform Relaunch",
                            UserId = "demo-user-123"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedDate = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7924),
                            Description = "Comprehensive brand strategy documentation including market analysis, competitive positioning, brand guidelines, and implementation roadmap. Focus on digital transformation and brand consistency across all touchpoints.",
                            EndDate = new DateTime(2025, 12, 23, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7923),
                            HourlyRate = 60.00m,
                            LastModified = new DateTime(2025, 11, 8, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7925),
                            StartDate = new DateTime(2025, 10, 24, 13, 29, 48, 949, DateTimeKind.Utc).AddTicks(7922),
                            Status = 1,
                            Title = "2026 Brand Strategy Documentation",
                            UserId = "demo-user-123"
                        });
                });

            modelBuilder.Entity("ProTrack.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("InvoiceTimeEntries", b =>
                {
                    b.HasOne("ProTrack.Models.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProTrack.Models.TimeEntry", null)
                        .WithMany()
                        .HasForeignKey("TimeEntriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProTrack.Models.Client", b =>
                {
                    b.HasOne("ProTrack.Models.ApplicationUser", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProTrack.Models.Invoice", b =>
                {
                    b.HasOne("ProTrack.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTrack.Models.ApplicationUser", "User")
                        .WithMany("Invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProTrack.Models.Project", b =>
                {
                    b.HasOne("ProTrack.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTrack.Models.ApplicationUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProTrack.Models.TimeEntry", b =>
                {
                    b.HasOne("ProTrack.Models.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTrack.Models.ApplicationUser", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProTrack.Models.ApplicationUser", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Invoices");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("ProTrack.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProTrack.Models.Project", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
